### PR TITLE
Base url change 

### PR DESCRIPTION
**Pull request by kvns07**

### CODE REVIEW

**Comment by TreavVasu** [comment]
- Name the Commit right next time 
- Replace  pubspec-lock with the original file in the current repo
  [Reason, give it a read](https://gpalma.pt/blog/what-is-the-pubspec-lock/)

**Comment by kvns07** [comment]
> * Name the Commit right next time
> * Replace  pubspec-lock with the original file in the current repo
>   [Reason, give it a read](https://gpalma.pt/blog/what-is-the-pubspec-lock/)

**Comment by kvns07** [comment]
Ok Sir

**Comment by TreavVasu** [comment]
@kvns07 why did you close the pr? Just do another commit

**Comment by kvns07** [comment]
Sorry sir, pr?

**Comment by kvns07** [comment]
Ok sir

**Comment by kvns07** [comment]
Will do it after replacing pubspec-lock

**Comment by TreavVasu** [comment]
screenshot-github com-2022 08 24-23_54_36
Next Time write something else here

**Comment by kvns07** [comment]
Sure sir.

**Pull request merged**
